# Generated by Skyramp v1.3.13 on 2026-03-16 17:26:17.769346792 +0000 UTC m=+168.574370563
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_integration_author_profile_field_validation.py \
# 		--output-dir /home/runner/work/fastapi-realworld-example-app/fastapi-realworld-example-app/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/fastapi-realworld-example-app/fastapi-realworld-example-app/skyramp-tests/scenario_author_profile_field_validation_1742137200.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    username = "fieldvalidation1742137200"

    # Request Body
    users_POST_request_body = r'''{
        "user": {
            "email": "fieldvalidation1742137200@example.com",
            "password": "Test1234!",
            "username": "fieldvalidation1742137200"
        }
    }'''
    
    # Execute Request
    users_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/users",
        method="POST",
        body=users_POST_request_body,
        headers=headers,
        data_override={"user.username": username}
    )
    # Generated Assertions
    assert users_POST_response.status_code == 201

    # Definition of authentication header
    token_from_users_post = {"Authorization": "Bearer " + skyramp.get_response_value(users_POST_response, "user.token")}

    # Request Body
    login_POST_request_body = r'''{
        "user": {
            "email": "fieldvalidation1742137200@example.com",
            "password": "Test1234!"
        }
    }'''
    
    # Execute Request
    login_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/users/login",
        method="POST",
        body=login_POST_request_body,
        headers=token_from_users_post
    )
    # Generated Assertions
    assert login_POST_response.status_code == 200

    # Request Body
    authors_POST_request_body = r'''{
        "author": {
            "location": "San Francisco",
            "specialty": "FastAPI Development",
            "website": "https://fieldvalidation.example.com"
        }
    }'''
    
    # Execute Request
    authors_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/authors",
        method="POST",
        body=authors_POST_request_body,
        headers=token_from_users_post
    )
    # Generated Assertions
    assert authors_POST_response.status_code == 201

    # Execute Request
    authors_authors_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/authors/{authors}",
        method="GET",
        headers=token_from_users_post,
        path_params={"authors": skyramp.get_response_value(login_POST_response, "user.username")}
    )
    # Generated Assertions
    assert authors_authors_GET_response.status_code == 200

    # Execute Request
    authors_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/authors",
        method="GET",
        headers=token_from_users_post
    )
    # Generated Assertions
    assert authors_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
