# Generated by Skyramp v1.3.13 on 2026-03-16 18:32:50.568385192 +0000 UTC m=+260.519707643
# Command: skyramp generate fuzz rest http://localhost:8000/api/authors \
# 		--api-schema http://localhost:8000/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method DELETE \
# 		--output test_fuzz_authors_delete.py \
# 		--output-dir /home/runner/work/fastapi-realworld-example-app/fastapi-realworld-example-app/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# fuzz test for /api/authors DELETE
def test_authors_delete():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    authors_DELETE_response = client.send_request(
        url=URL,
        path="/api/authors",
        method="DELETE",
        headers=headers,
        expected_code="20x"
    )

    assert client.is_success()


if __name__ == "__main__":
    test_authors_delete()
