# Generated by Skyramp v1.3.13 on 2026-03-16 16:55:48.514566927 +0000 UTC m=+259.897006015
# Command: skyramp generate contract rest http://localhost:8000/api/authors \
# 		--api-schema http://localhost:8000/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method DELETE \
# 		--output test_contract_authors_delete.py \
# 		--output-dir /home/runner/work/fastapi-realworld-example-app/fastapi-realworld-example-app/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/authors DELETE
def test_authors_delete():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    authors_DELETE_response = client.send_request(
        url=URL,
        path="/api/authors",
        method="DELETE",
        headers=headers
    )

    # Generated Assertions
    assert authors_DELETE_response.status_code == 204


if __name__ == "__main__":
    test_authors_delete()
