# Generated by Skyramp v1.3.13 on 2026-03-16 16:56:43.667168403 +0000 UTC m=+315.049607491
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_integration_author_unauthorized_access.py \
# 		--output-dir /home/runner/work/fastapi-realworld-example-app/fastapi-realworld-example-app/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/fastapi-realworld-example-app/fastapi-realworld-example-app/skyramp-tests/scenario_author_unauthorized_access_1742122800.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    authors_POST_request_body = r'''{
        "author": {
            "location": "Nowhere",
            "specialty": "Unauthorized Test",
            "website": "https://test.example.com"
        }
    }'''
    
    # Execute Request
    authors_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/authors",
        method="POST",
        body=authors_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert authors_POST_response.status_code == 403

    # Request Body
    authors_PUT_request_body = r'''{
        "author": {
            "location": "Nowhere",
            "specialty": "Unauthorized Update",
            "website": "https://test.example.com"
        }
    }'''
    
    # Execute Request
    authors_PUT_response = client.send_request(
        url=URL_localhost,
        path="/api/authors",
        method="PUT",
        body=authors_PUT_request_body,
        headers=headers
    )
    # Generated Assertions
    assert authors_PUT_response.status_code == 403

    # Execute Request
    authors_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/authors",
        method="DELETE",
        headers=headers
    )
    # Generated Assertions
    assert authors_DELETE_response.status_code == 403


if __name__ == "__main__":
    test_integration()
