# Generated by Skyramp v1.3.13 on 2026-03-16 18:33:14.487319194 +0000 UTC m=+284.438641635
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_integration_author_user_linkage.py \
# 		--output-dir /home/runner/work/fastapi-realworld-example-app/fastapi-realworld-example-app/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/fastapi-realworld-example-app/fastapi-realworld-example-app/skyramp-tests/scenario_author_user_linkage_1742160000.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    username = "authlink1742160000"

    # Request Body
    users_POST_request_body = r'''{
        "user": {
            "email": "authlink1742160000@example.com",
            "password": "Test1234!",
            "username": "authlink1742160000"
        }
    }'''
    
    # Execute Request
    users_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/users",
        method="POST",
        body=users_POST_request_body,
        headers=headers,
        data_override={"user.username": username}
    )
    # Generated Assertions
    assert users_POST_response.status_code == 201

    # Request Body
    authors_POST_request_body = r'''{
        "author": {
            "location": "Berlin",
            "specialty": "Software Engineering",
            "website": "https://authlink.example.com"
        }
    }'''
    
    # Execute Request
    authors_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/authors",
        method="POST",
        body=authors_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert authors_POST_response.status_code == 201

    # Execute Request
    authors_authors_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/authors/{authors}",
        method="GET",
        headers=headers,
        path_params={"authors": skyramp.get_response_value(authors_POST_response, "author.username")}
    )
    # Generated Assertions
    assert authors_authors_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
