# Generated by Skyramp v1.3.13 on 2026-03-16 14:12:02.057653839 +0000 UTC m=+111.636337613
# Command: skyramp generate contract rest http://localhost:8000/api/health \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_health_contract.py \
# 		--output-dir /home/runner/work/fastapi-realworld-example-app/fastapi-realworld-example-app/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/health GET
def test_health_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    health_GET_response = client.send_request(
        url=URL,
        path="/api/health",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(health_GET_response, "20x")
    assert skyramp.get_response_value(health_GET_response, "status") is not None
    assert skyramp.get_response_value(health_GET_response, "version") is not None
    assert skyramp.get_response_value(health_GET_response, "environment") is not None


if __name__ == "__main__":
    test_health_get()
