# Generated by Skyramp v1.3.13 on 2026-03-16 18:01:52.844124334 +0000 UTC m=+164.137852601
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_integration_author_duplicate_creation_error.py \
# 		--output-dir /home/runner/work/fastapi-realworld-example-app/fastapi-realworld-example-app/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/fastapi-realworld-example-app/fastapi-realworld-example-app/skyramp-tests/scenario_author_duplicate_creation_error_1742130000.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    users_POST_request_body = r'''{
        "user": {
            "email": "dupauthor1742130000@example.com",
            "password": "Test1234!",
            "username": "dupauthor1742130000"
        }
    }'''
    
    # Execute Request
    users_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/users",
        method="POST",
        body=users_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert users_POST_response.status_code == 201

    # Request Body
    authors_POST_request_body = r'''{
        "author": {
            "location": "New York",
            "specialty": "Python Development",
            "website": "https://dupauthor.example.com"
        }
    }'''
    
    # Execute Request
    authors_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/authors",
        method="POST",
        body=authors_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert authors_POST_response.status_code == 201

    # Request Body
    authors_POST_1_request_body = r'''{
        "author": {
            "location": "San Francisco",
            "specialty": "Machine Learning",
            "website": "https://dupauthor2.example.com"
        }
    }'''
    
    # Execute Request
    authors_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/authors",
        method="POST",
        body=authors_POST_1_request_body,
        headers=headers
    )
    # Generated Assertions
    assert authors_POST_1_response.status_code == 400


if __name__ == "__main__":
    test_integration()
