# Generated by Skyramp v1.3.13 on 2026-03-16 17:47:08.287781928 +0000 UTC m=+162.307895129
# Command: skyramp generate contract rest http://localhost:8000/api/authors \
# 		--api-schema http://localhost:8000/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_contract_authors_post.py \
# 		--output-dir /home/runner/work/fastapi-realworld-example-app/fastapi-realworld-example-app/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"author":{"specialty":"Python Development","location":"New York","website":"https://example.com"}} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/authors POST
def test_authors_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    authors_POST_request_body = r'''{
        "author": {
            "location": "New York",
            "specialty": "Python Development",
            "website": "https://example.com"
        }
    }'''

    # Expected Response Body
    expected_authors_POST_response_body = r'''{
        "author": {
            "createdAt": "2026-03-16T17:47:08Z",
            "id": 0,
            "location": "",
            "specialty": "",
            "updatedAt": "2026-03-16T17:47:08Z",
            "userId": 0,
            "username": "string",
            "website": ""
        }
    }'''

    # Execute Request
    authors_POST_response = client.send_request(
        url=URL,
        path="/api/authors",
        method="POST",
        body=authors_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert authors_POST_response.status_code == 201
    assert skyramp.check_schema(authors_POST_response, expected_authors_POST_response_body)
    assert skyramp.get_response_value(authors_POST_response, "author.createdAt") is not None
    assert skyramp.get_response_value(authors_POST_response, "author.id") is not None
    assert skyramp.get_response_value(authors_POST_response, "author.location") is not None


if __name__ == "__main__":
    test_authors_post()
