# Generated by Skyramp v1.3.13 on 2026-03-16 16:04:49.602811033 +0000 UTC m=+130.782468705
# Command: skyramp generate fuzz rest http://localhost:8000/api/authors \
# 		--api-schema http://localhost:8000/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_fuzz_authors_post.py \
# 		--output-dir /home/runner/work/fastapi-realworld-example-app/fastapi-realworld-example-app/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"author":{"specialty":"Python Development","location":"New York","website":"https://testauthor.example.com"}} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# fuzz test for /api/authors POST
def test_authors_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    authors_POST_request_body = r'''{
      "author": {
        "specialty": "Python Development",
        "location": "New York",
        "website": "https://testauthor.example.com"
      }
    }'''
    
    # Fuzz strategies
    authors_post_fuzzed_body = {"author": {
            "location": "0123456789",
            "specialty": "0123456789",
            "website": "0123456789"
        }}
    # Fuzz status codes
    expected_authors_post_status_code = {"author": {
            "location": "40x",
            "specialty": "40x",
            "website": "40x"
        }}
    # Fuzz status codes for Null values
    expected_authors_post_null_status_code = {"author": {
            "location": "40x",
            "specialty": "40x",
            "website": "40x"
        }}

    # Execute Request
    authors_POST_response = client.send_request(
        url=URL,
        path="/api/authors",
        method="POST",
        body=authors_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(authors_post_fuzzed_body):
        # Execute Request
        authors_POST_response = client.send_request(
            url=URL,
            path="/api/authors",
            method="POST",
            body=authors_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(authors_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_authors_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(authors_post_fuzzed_body, key) }'
        )

        # Execute Request
        authors_POST_response = client.send_request(
            url=URL,
            path="/api/authors",
            method="POST",
            body=authors_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_authors_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_authors_post()
