# Generated by Skyramp v1.3.13 on 2026-03-16 16:42:29.82774893 +0000 UTC m=+149.651070011
# Command: skyramp generate contract rest http://localhost:8000/api/authors/testauthor1 \
# 		--api-schema http://localhost:8000/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_contract_authors_get_by_username.py \
# 		--output-dir /home/runner/work/fastapi-realworld-example-app/fastapi-realworld-example-app/tests \
# 		--overwrite \
# 		--path-params username=testauthor1 \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/authors/testauthor1 GET
def test_testauthor_1_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_testauthor1_GET_response_body = r'''{
        "author": {
            "createdAt": "2026-03-16T16:42:29Z",
            "id": 0,
            "location": "",
            "specialty": "",
            "updatedAt": "2026-03-16T16:42:29Z",
            "userId": 0,
            "username": "string",
            "website": ""
        }
    }'''

    # Execute Request
    testauthor1_GET_response = client.send_request(
        url=URL,
        path="/api/authors/testauthor1",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert testauthor1_GET_response.status_code == 200
    assert skyramp.check_schema(testauthor1_GET_response, expected_testauthor1_GET_response_body)
    assert skyramp.get_response_value(testauthor1_GET_response, "author.createdAt") is not None
    assert skyramp.get_response_value(testauthor1_GET_response, "author.id") is not None
    assert skyramp.get_response_value(testauthor1_GET_response, "author.location") is not None


if __name__ == "__main__":
    test_testauthor_1_get()
