# Generated by Skyramp v1.3.13 on 2026-03-16 16:42:57.025464821 +0000 UTC m=+176.848785987
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_integration_duplicate_author_prevention.py \
# 		--output-dir /home/runner/work/fastapi-realworld-example-app/fastapi-realworld-example-app/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/fastapi-realworld-example-app/fastapi-realworld-example-app/tests/scenario_duplicate_author_prevention.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    users_POST_request_body = r'''{
        "user": {
            "email": "dupauthor@example.com",
            "password": "Test1234!",
            "username": "dupauthor"
        }
    }'''
    
    # Execute Request
    users_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/users",
        method="POST",
        body=users_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert users_POST_response.status_code == 201

    # Request Body
    login_POST_request_body = r'''{
        "user": {
            "email": "dupauthor@example.com",
            "password": "Test1234!"
        }
    }'''
    
    # Execute Request
    login_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/users/login",
        method="POST",
        body=login_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert login_POST_response.status_code == 200

    # Request Body
    authors_POST_request_body = r'''{
        "author": {
            "location": "New York",
            "specialty": "Python Development",
            "website": "https://dupauthor.example.com"
        }
    }'''
    
    # Execute Request
    authors_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/authors",
        method="POST",
        body=authors_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert authors_POST_response.status_code == 201

    # Request Body
    authors_POST_1_request_body = r'''{
        "author": {
            "location": "Chicago",
            "specialty": "Django Developer",
            "website": "https://duplicate.example.com"
        }
    }'''
    
    # Execute Request
    authors_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/authors",
        method="POST",
        body=authors_POST_1_request_body,
        headers=headers
    )
    # Generated Assertions
    assert authors_POST_1_response.status_code == 400


if __name__ == "__main__":
    test_integration()
