# Generated by Skyramp v1.3.13 on 2026-03-16 16:04:56.545158186 +0000 UTC m=+137.724815849
# Command: skyramp generate contract rest http://localhost:8000/api/authors \
# 		--api-schema http://localhost:8000/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_contract_authors_list.py \
# 		--output-dir /home/runner/work/fastapi-realworld-example-app/fastapi-realworld-example-app/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/authors GET
def test_authors_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_authors_GET_response_body = r'''{
        "authors": [
            {
                "createdAt": "2026-03-16T16:04:56Z",
                "id": 0,
                "location": "",
                "specialty": "",
                "updatedAt": "2026-03-16T16:04:56Z",
                "userId": 0,
                "username": "string",
                "website": ""
            }
        ],
        "authorsCount": 0
    }'''

    # Execute Request
    authors_GET_response = client.send_request(
        url=URL,
        path="/api/authors",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert authors_GET_response.status_code == 200
    assert skyramp.check_schema(authors_GET_response, expected_authors_GET_response_body)
    assert skyramp.get_response_value(authors_GET_response, "authors.0.createdAt") is not None
    assert skyramp.get_response_value(authors_GET_response, "authors.0.id") is not None
    assert skyramp.get_response_value(authors_GET_response, "authors.0.location") is not None


if __name__ == "__main__":
    test_authors_get()
